version: '3.8'

services:
  product-details-service:
    build: ./product-details-service
    container_name: product-details-service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  dealer-pricing-service:
    build: ./dealer-pricing-service
    container_name: dealer-pricing-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  frontend-service:
    build: ./frontend-service
    container_name: frontend-service
    ports:
      - "8080:8080"
    depends_on:
      - product-details-service
      - dealer-pricing-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  default:
    driver: bridge