# Product Details Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-details-deployment
  labels:
    app: product-details-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-details-service
  template:
    metadata:
      labels:
        app: product-details-service
    spec:
      containers:
      - name: product-details
        image: product-details-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
# Product Details Service
apiVersion: v1
kind: Service
metadata:
  name: product-details-service
spec:
  selector:
    app: product-details-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
# Dealer Pricing Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealer-pricing-deployment
  labels:
    app: dealer-pricing-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dealer-pricing-service
  template:
    metadata:
      labels:
        app: dealer-pricing-service
    spec:
      containers:
      - name: dealer-pricing
        image: dealer-pricing-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
# Dealer Pricing Service
apiVersion: v1
kind: Service
metadata:
  name: dealer-pricing-service
spec:
  selector:
    app: dealer-pricing-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
# Frontend Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend
        image: frontend-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer